name: CI
on: 
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm dedupe -check
      - run: pnpm build
  check:
    name: Check for type issues with astro check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm check
  all-systems-pass:
    needs: [check,build]
    name: All systems pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4